Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      ## Generate a name based on the stage
      UserPoolName: mysite_sa_user_pool_${self:custom.stage}
      ## Set email as an alias
      UsernameAttributes:
        - email ## telling the User Pool that we want our users to be able to log in with their email as their username
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ## Generate an app client name based on the stage
      ClientName: mysite_sa_user_pool_client_${self:custom.stage}
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

## We want CloudFormation to tell us the User Pool Id and the User Pool Client Id that is generated
## Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
