Resources:
  CertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNameCerts}
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
        - AttributeName: CompletionDate
          AttributeType: S
        - AttributeName: Enabled
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH
        - AttributeName: CompletionDate
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: EnabledIndex
          KeySchema:
            - AttributeName: Enabled
              KeyType: HASH
            - AttributeName: CompletionDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      ## Set the capacity to auto-scale
      ### PAY_PER_REQUEST (On-Demand Capacity): for starting out, and workloads are not very predictable or stable
      ### Provisioned Capacity: cheaper when knowing exactly how much capacity is needed
      BillingMode: PAY_PER_REQUEST
    ## To prevent accidentally deleting serverless resources (DynamoDB in this case)
    ### e.g with a typo in the resource name (NotesTable), the old table will be removed and a new one will be created in place
    DeletionPolicy: Retain
